const ADMIN_PROGRESS_KEY = "tomcodex.adminCourseProgress.v1";
const modules = [
  { title: "Salesforce Platform Foundations", description: "Understand CRM, Salesforce architecture, Setup, apps, objects, records, and the administrator role.", points: ["Explain CRM and how Salesforce supports business teams.", "Navigate Setup, App Launcher, Object Manager, and list views.", "Understand standard objects, custom objects, fields, and records."], resources: [["Salesforce CRM Trailhead", "https://trailhead.salesforce.com/content/learn/modules/lex_implementation_basics"], ["Salesforce Help", "https://help.salesforce.com/"], ["What Is Salesforce? Video", "https://www.salesforce.com/products/what-is-salesforce/video/"]], practice: ["Create a Trailhead Playground or Developer Edition org.", "Explore Setup and identify five administrator tools.", "Create a simple custom app and navigation items."], questions: ["What is metadata in Salesforce?", "How are objects, fields, and records related?", "Which Setup tools would you use daily as an admin?"] },
  { title: "Data Modeling and Relationships", description: "Design reliable Salesforce data structures using objects, fields, relationships, and Schema Builder.", points: ["Choose correct field types for business requirements.", "Compare Lookup and Master-Detail relationships.", "Use junction objects and roll-up summaries."], resources: [["Trailhead Data Modeling", "https://trailhead.salesforce.com/content/learn/modules/data_modeling"], ["Object Reference", "https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/"]], practice: ["Create an Incident custom object.", "Connect Accounts to Incidents.", "Map the data model in Schema Builder."], questions: ["When should you use Master-Detail?", "What does a junction object solve?", "How can a poor data model affect reporting?"] },
  { title: "User Access and Security", description: "Protect Salesforce data with least-privilege access and scalable sharing.", points: ["Understand users, profiles, permission sets, and permission set groups.", "Set organization-wide defaults and role hierarchy.", "Use sharing rules, teams, and field-level security."], resources: [["Trailhead Data Security", "https://trailhead.salesforce.com/content/learn/modules/data_security"], ["Salesforce Security Guide", "https://help.salesforce.com/s/articleView?id=sf.security_data_access.htm&type=5"]], practice: ["Create a permission set for Incident Managers.", "Design private record access with sharing rules.", "Test field visibility for two user personas."], questions: ["Profile versus Permission Set?", "Why start with restrictive OWD?", "How do object, field, and record access combine?"] },
  { title: "Data Management and Quality", description: "Import, update, clean, protect, and maintain trustworthy Salesforce data.", points: ["Choose between Data Import Wizard and Data Loader.", "Prevent duplicate and invalid records.", "Plan backups and safe bulk changes."], resources: [["Trailhead Data Management", "https://trailhead.salesforce.com/content/learn/modules/lex_implementation_data_management"], ["Data Loader Guide", "https://developer.salesforce.com/docs/atlas.en-us.dataLoader.meta/dataLoader/"]], practice: ["Import sample Incident records.", "Create a matching and duplicate rule.", "Document a safe data update checklist."], questions: ["What should happen before a bulk update?", "How do external IDs help?", "How do you measure data quality?"] },
  { title: "Forms, Validation, and User Experience", description: "Create efficient record experiences and enforce business rules without code.", points: ["Customize page layouts and Lightning record pages.", "Build formula fields and validation rules.", "Use Dynamic Forms, actions, and compact layouts."], resources: [["Lightning Experience Customization", "https://trailhead.salesforce.com/content/learn/modules/lex_customization"], ["Formulas and Validations", "https://trailhead.salesforce.com/content/learn/modules/point_click_business_logic"]], practice: ["Create role-specific Incident page layouts.", "Build an Incident Age formula.", "Prevent invalid critical incident records."], questions: ["Validation rule versus required field?", "Page layout versus Lightning page?", "How do you reduce user clicks?"] },
  { title: "Flow Automation", description: "Automate business processes safely using Salesforce Flow.", points: ["Choose Screen, Record-Triggered, Scheduled, or Autolaunched Flow.", "Use decisions, loops, assignments, and fault paths.", "Design maintainable automation and avoid recursion."], resources: [["Flow Builder Basics", "https://trailhead.salesforce.com/content/learn/modules/flow-basics"], ["Flow Builder Guide", "https://help.salesforce.com/s/articleView?id=sf.flow.htm&type=5"]], practice: ["Build an Incident creation Screen Flow.", "Notify users when an Incident becomes critical.", "Add a fault path and test negative scenarios."], questions: ["When should a flow run before save?", "Why are fault paths important?", "How do you prevent conflicting automation?"] },
  { title: "Reports and Dashboards", description: "Turn Salesforce data into useful operational and leadership insights.", points: ["Build tabular, summary, matrix, and joined reports.", "Use report types, filters, grouping, and formulas.", "Design dashboards for specific audiences."], resources: [["Reports and Dashboards Trailhead", "https://trailhead.salesforce.com/content/learn/modules/lex_implementation_reports_dashboards"], ["Reports Help", "https://help.salesforce.com/s/articleView?id=sf.reports.htm&type=5"]], practice: ["Build an Incident operational report.", "Create a management dashboard.", "Validate report access for multiple users."], questions: ["What controls which records appear in a report?", "When is a custom report type required?", "What makes a dashboard actionable?"] },
  { title: "Workplace Admin and Continuous Growth", description: "Apply admin skills after placement through support, governance, releases, and continuous improvement.", points: ["Investigate user issues and communicate resolutions.", "Manage requirements, sandboxes, testing, and releases.", "Track Salesforce releases and improve the org continuously."], resources: [["Salesforce Release Notes", "https://help.salesforce.com/s/articleView?id=release-notes.salesforce_release_notes.htm&type=5"], ["Salesforce Admins", "https://admin.salesforce.com/"], ["Trailhead Admin Career", "https://trailhead.salesforce.com/career-path/admin"]], practice: ["Resolve a simulated production support ticket.", "Plan and test a small release.", "Create a quarterly org health review."], questions: ["How do you investigate a user issue?", "What belongs in a release checklist?", "How do you prioritize admin improvements?"] },
  { title: "Advanced Security and Identity", description: "Design and audit enterprise-grade access across users, records, fields, sessions, and connected systems.", points: ["Use permission set groups, muting permissions, restriction rules, and scoping rules.", "Understand SSO, MFA, login policies, session security, and identity governance.", "Audit access using setup tools, reports, and security reviews."], resources: [["Identity Basics Trailhead", "https://trailhead.salesforce.com/content/learn/modules/identity_basics"], ["Data Security Trailhead", "https://trailhead.salesforce.com/content/learn/modules/data_security"], ["Salesforce Security Guide", "https://help.salesforce.com/s/articleView?id=sf.security.htm&type=5"]], practice: ["Design access for employees, managers, partners, and auditors.", "Create and document a permission set group strategy.", "Perform a simulated quarterly access review."], questions: ["When should restriction rules be used?", "How do permission set groups improve governance?", "What evidence belongs in an access audit?"] },
  { title: "Advanced Flow Architecture", description: "Build scalable, testable, and maintainable automation across complex business processes.", points: ["Design reusable subflows and consistent fault handling.", "Use asynchronous paths, scheduled paths, platform events, and orchestration concepts.", "Analyze Flow limits, order of execution, recursion, and performance."], resources: [["Flow Builder Trailhead", "https://trailhead.salesforce.com/content/learn/trails/build-flows-with-flow-builder"], ["Flow Best Practices", "https://help.salesforce.com/s/articleView?id=sf.flow_concepts_bestpractices.htm&type=5"], ["Architect Decision Guides", "https://architect.salesforce.com/decision-guides"]], practice: ["Refactor a large Flow into reusable subflows.", "Create centralized error logging and notifications.", "Review automation for recursion and performance risk."], questions: ["When should automation move from Flow to Apex?", "How do you design fault handling at scale?", "How does order of execution affect automation?"] },
  { title: "Org Governance and Center of Excellence", description: "Create standards and decision processes that keep Salesforce maintainable as teams and requirements grow.", points: ["Establish intake, prioritization, naming, documentation, and ownership standards.", "Design a Salesforce Center of Excellence and governance cadence.", "Manage technical debt, stakeholder expectations, and platform roadmap."], resources: [["Well-Architected Framework", "https://architect.salesforce.com/well-architected/overview"], ["Salesforce Architects", "https://architect.salesforce.com/"], ["Salesforce Admins", "https://admin.salesforce.com/"]], practice: ["Create a governance charter and intake process.", "Build a technical-debt register.", "Run a simulated architecture and change review."], questions: ["What decisions belong to a Center of Excellence?", "How do you prioritize technical debt?", "How does governance improve delivery speed?"] },
  { title: "Release Management and DevOps for Admins", description: "Move declarative changes safely across environments using modern release practices.", points: ["Understand sandbox strategy, source control, change sets, DevOps Center, and deployment validation.", "Plan testing, rollback, communication, and post-deployment verification.", "Coordinate declarative and coded changes across teams."], resources: [["DevOps Center Trailhead", "https://trailhead.salesforce.com/content/learn/modules/devops-center-basics"], ["Application Lifecycle Management", "https://trailhead.salesforce.com/content/learn/modules/application-lifecycle-and-development-models"], ["Salesforce CLI Docs", "https://developer.salesforce.com/tools/salesforcecli"]], practice: ["Create a release plan for a multi-feature deployment.", "Validate dependencies and build a rollback plan.", "Document a post-deployment verification checklist."], questions: ["What makes a sandbox strategy effective?", "Why use source control for admin changes?", "What should happen when deployment validation fails?"] },
  { title: "Org Health, Scale, and Performance", description: "Monitor and improve a growing Salesforce org before issues affect users or delivery.", points: ["Review limits, storage, automation complexity, data skew, and report performance.", "Use Optimizer, Health Check, debug tools, and adoption metrics.", "Plan archiving, cleanup, and performance improvement work."], resources: [["Salesforce Optimizer", "https://help.salesforce.com/s/articleView?id=sf.optimizer.htm&type=5"], ["Scale Center", "https://help.salesforce.com/s/articleView?id=sf.scale_center.htm&type=5"], ["Well-Architected Performance", "https://architect.salesforce.com/well-architected/reliable/performance"]], practice: ["Complete a simulated org health assessment.", "Identify and prioritize three performance risks.", "Create a data archival and cleanup proposal."], questions: ["What causes data skew?", "How do you measure org health?", "When should data be archived?"] },
  { title: "Senior Admin Leadership and Strategy", description: "Operate as a senior administrator who connects platform decisions to measurable business outcomes.", points: ["Lead discovery, roadmap planning, stakeholder communication, and adoption strategy.", "Coach users and junior admins while setting platform standards.", "Measure business value, delivery outcomes, risk, and continuous improvement."], resources: [["Admin Career Path", "https://trailhead.salesforce.com/career-path/admin"], ["Business Analyst Trailhead", "https://trailhead.salesforce.com/content/learn/trails/get-started-as-a-salesforce-business-analyst"], ["Salesforce Admins Podcast", "https://admin.salesforce.com/blog/category/podcast"]], practice: ["Present a twelve-month Salesforce roadmap.", "Create an executive value and risk summary.", "Coach a junior admin through a solution review."], questions: ["How does a senior admin influence strategy?", "Which metrics demonstrate Salesforce value?", "How do you balance urgent requests with roadmap priorities?"] }
];

window.TomCodexAdminModules = modules;
/*
let currentModule = 0;
let completed = loadProgress();
const byId = (id) => document.getElementById(id);

function loadProgress() { try { return JSON.parse(localStorage.getItem(ADMIN_PROGRESS_KEY)) || []; } catch { return []; } }
function saveProgress() { localStorage.setItem(ADMIN_PROGRESS_KEY, JSON.stringify(completed)); }
function renderNav() { byId("moduleNav").innerHTML = modules.map((module, index) => `<button type="button" data-module="${index}" class="${index === currentModule ? "active" : ""} ${completed.includes(index) ? "done" : ""}"><span class="module-number">${completed.includes(index) ? "✓" : index + 1}</span><span><strong>${module.title}</strong><span>${completed.includes(index) ? "Completed" : "Ready to learn"}</span></span></button>`).join(""); document.querySelectorAll("[data-module]").forEach((button) => button.addEventListener("click", () => { currentModule = Number(button.dataset.module); render(); })); }
function renderProgress() { const progress = Math.round(completed.length / modules.length * 100); byId("courseProgressText").textContent = `${progress}%`; byId("completedModulesText").textContent = `${completed.length} / ${modules.length}`; byId("courseProgressBar").style.width = `${progress}%`; }
function render() { const module = modules[currentModule]; byId("moduleLabel").textContent = `Module ${currentModule + 1} of ${modules.length}`; byId("moduleTitle").textContent = module.title; byId("moduleDescription").textContent = module.description; byId("lessonPoints").innerHTML = module.points.map((item) => `<div>${item}</div>`).join(""); byId("resourceList").innerHTML = module.resources.map(([name,url]) => `<a href="${url}" target="_blank" rel="noopener noreferrer">${name}<span>↗</span></a>`).join(""); byId("practiceList").innerHTML = module.practice.map((item) => `<div>${item}</div>`).join(""); byId("questionList").innerHTML = module.questions.map((item) => `<div>${item}</div>`).join(""); const done = completed.includes(currentModule); byId("completeModuleBtn").textContent = done ? "Module completed" : "Mark module complete"; byId("completeModuleBtn").classList.toggle("done", done); byId("previousModuleBtn").disabled = currentModule === 0; byId("nextModuleBtn").textContent = currentModule === modules.length - 1 ? "Continue in dashboard" : "Next module"; renderNav(); renderProgress(); }
byId("completeModuleBtn").addEventListener("click", () => { if (!completed.includes(currentModule)) { completed.push(currentModule); saveProgress(); window.TomCodexLearning?.record("task", 10, `Salesforce Admin module: ${modules[currentModule].title}`); } render(); });
byId("previousModuleBtn").addEventListener("click", () => { if (currentModule > 0) { currentModule -= 1; render(); } });
byId("nextModuleBtn").addEventListener("click", () => { if (currentModule < modules.length - 1) { currentModule += 1; render(); } else window.location.href = "dashboard.html"; });
byId("continueCourseBtn").addEventListener("click", () => { currentModule = modules.findIndex((_, index) => !completed.includes(index)); if (currentModule < 0) currentModule = modules.length - 1; render(); byId("moduleContent").scrollIntoView({ behavior: "smooth" }); });
render();
*/
